### PR TITLE
Update to 3.22.19, disable gconf

### LINKED ISSUE #2: Save settings changes
```
GConf Error: Failed to activate configuration server: The name org.gnome.GConf was not provided by any .service files


(sol:3): GConf-WARNING **: 14:47:55.413: Directory `/apps/aisleriot' was not being monitored by GConfClient 0xd77f60
```

We're not actually saving settings changes for aisleriot, which isn't ideal.

### PR DESCRIPTION
**Pull request by shuliande**
Hi! This commit should fix #2 for gnome users.

### CODE REVIEW

**Comment by grdryn** [comment]
I actually came here to see if there was an open issue open for this, so delighted to see you've already got a PR! I get a 404 when trying to install the CI build to test it out, I guess it expires them after a short period of time?

This should allow settings (and stats also I think?) to be persisted again, on systems that don't have gconf. WDYT @hfiguiere   @bilelmoussaoui ?

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
feel free to try this fresh build.

**Comment by grdryn** [comment]
That works great, thanks @hfiguiere. I can confirm that this fixes so that settings and statistics are persisted on close/restart, where they weren't before, on GNOME on Fedora 35.

**Review by grdryn — APPROVED** [review]

**Pull request merged**
